# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedasset',
            options={'verbose_name': 'Fixed Asset', 'verbose_name_plural': 'Fixed Assets'},
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='AssetID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Asset ID'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='AssetName',
            field=models.CharField(max_length=200, verbose_name='Asset Name'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='AssetNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Asset Notes'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='AssetTagNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Tag Number'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='CurrentValue',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Current Value'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='DepreciationMethod',
            field=models.CharField(max_length=50, verbose_name='Depreciation Method'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='DisposalDate',
            field=models.DateField(blank=True, null=True, verbose_name='Disposal Date'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='PurchaseCost',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Purchase Cost'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='PurchaseDate',
            field=models.DateField(verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='UsefulLifeYears',
            field=models.IntegerField(verbose_name='Useful Life (Years)'),
        ),
    ]
