# Generated by Django 5.0.14 on 2025-07-25 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('core', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(db_column='ProjectID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_column='ProjectName', max_length=255)),
                ('start_date', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('budget', models.DecimalField(blank=True, db_column='Budget', decimal_places=2, max_digits=15, null=True)),
                ('project_notes', models.TextField(blank=True, db_column='ProjectNotes', null=True)),
                ('status', models.CharField(db_column='Status', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(db_column='CustomerID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.customer')),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('time_entry_id', models.AutoField(db_column='TimeEntryID', primary_key=True, serialize=False)),
                ('work_date', models.DateField(db_column='WorkDate')),
                ('hours', models.DecimalField(db_column='Hours', decimal_places=2, max_digits=5)),
                ('time_entry_notes', models.TextField(blank=True, db_column='TimeEntryNotes', null=True)),
                ('billable', models.BooleanField(db_column='Billable', default=True)),
                ('rate', models.DecimalField(blank=True, db_column='Rate', decimal_places=2, max_digits=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, to='project_tracking.project')),
            ],
            options={
                'verbose_name_plural': 'Time Entries',
                'db_table': 'TimeEntries',
            },
        ),
    ]
