# Generated by Django 5.2.4 on 2025-07-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('payment_terms', models.CharField(blank=True, db_column='PaymentTerms', max_length=100, null=True)),
                ('customer_notes', models.TextField(blank=True, db_column='CustomerNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(db_column='VendorID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('payment_terms', models.CharField(blank=True, db_column='PaymentTerms', max_length=100, null=True)),
                ('vendor_notes', models.TextField(blank=True, db_column='VendorNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'Vendors',
            },
        ),
    ]
