# Generated by Django 5.2.4 on 2025-07-22 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(db_column='BillID', primary_key=True, serialize=False)),
                ('bill_number', models.CharField(db_column='BillNumber', max_length=100)),
                ('bill_date', models.DateField(db_column='BillDate')),
                ('due_date', models.DateField(db_column='DueDate')),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=15)),
                ('status', models.CharField(db_column='Status', max_length=50)),
                ('bill_notes', models.TextField(blank=True, db_column='BillNotes', null=True)),
                ('currency_code', models.CharField(db_column='CurrencyCode', default='USD', max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(db_column='VendorID', on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
            options={
                'db_table': 'Bills',
                'unique_together': {('company', 'bill_number')},
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('line_item_id', models.AutoField(db_column='LineItemID', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='Description')),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('bill', models.ForeignKey(db_column='BillID', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payments.bill')),
                ('inventory', models.ForeignKey(blank=True, db_column='InventoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
            ],
            options={
                'db_table': 'BillLineItems',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(db_column='InvoiceID', primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(db_column='InvoiceNumber', max_length=100)),
                ('invoice_date', models.DateField(db_column='InvoiceDate')),
                ('due_date', models.DateField(db_column='DueDate')),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=15)),
                ('status', models.CharField(db_column='Status', max_length=50)),
                ('invoice_notes', models.TextField(blank=True, db_column='InvoiceNotes', null=True)),
                ('currency_code', models.CharField(db_column='CurrencyCode', default='USD', max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('subscription', models.ForeignKey(blank=True, db_column='SubscriptionID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription')),
                ('user', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Invoices',
                'unique_together': {('company', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('line_item_id', models.AutoField(db_column='LineItemID', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='Description')),
                ('quantity', models.DecimalField(db_column='Quantity', decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(db_column='TotalAmount', decimal_places=2, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('inventory', models.ForeignKey(blank=True, db_column='InventoryID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
                ('invoice', models.ForeignKey(db_column='InvoiceID', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='payments.invoice')),
            ],
            options={
                'db_table': 'InvoiceLineItems',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('payment_date', models.DateField(db_column='PaymentDate')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(db_column='PaymentMethod', max_length=100)),
                ('payment_notes', models.TextField(blank=True, db_column='PaymentNotes', null=True)),
                ('currency_code', models.CharField(db_column='CurrencyCode', default='USD', max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('bill', models.ForeignKey(blank=True, db_column='BillID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.bill')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('invoice', models.ForeignKey(blank=True, db_column='InvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.invoice')),
                ('user', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
    ]
