# Generated by Django 5.0.14 on 2025-09-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bills', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('InventoryID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductCode', models.CharField(max_length=100)),
                ('ProductName', models.CharField(max_length=200)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=18)),
                ('CostPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('InventoryNotes', models.TextField(blank=True, null=True)),
                ('ValuationMethod', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('LineItemID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('BillID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
                ('InventoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
            ],
            options={
                'db_table': 'BillLineItems',
            },
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('LocationID', models.AutoField(primary_key=True, serialize=False)),
                ('LocationName', models.CharField(max_length=100)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'InventoryLocations',
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='LocationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorylocation'),
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('LineItemID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('UnitPrice', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('InventoryID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
                ('InvoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice')),
            ],
            options={
                'db_table': 'InvoiceLineItems',
            },
        ),
    ]
