# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_options_alter_invoice_companyid_and_more'),
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='inventorylocation',
            options={'verbose_name': 'Inventory Location', 'verbose_name_plural': 'Inventory Locations'},
        ),
        migrations.AlterModelOptions(
            name='invoicelineitem',
            options={'verbose_name': 'Invoice Line Item', 'verbose_name_plural': 'Invoice Line Items'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='CostPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Cost Price'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='InventoryID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Inventory ID'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='InventoryNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Inventory Notes'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='LocationID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorylocation', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ProductCode',
            field=models.CharField(max_length=100, verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ProductName',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='Quantity',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='UnitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Unit Price'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ValuationMethod',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valuation Method'),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='LocationID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Location ID'),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='LocationName',
            field=models.CharField(max_length=100, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='Description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='InventoryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory', verbose_name='Inventory Item'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='InvoiceID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='LineItemID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Line Item ID'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='Quantity',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='UnitPrice',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Unit Price'),
        ),
    ]
