# Generated by Django 5.2.4 on 2025-07-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(db_column='DocumentID', primary_key=True, serialize=False)),
                ('file_path', models.CharField(db_column='FilePath', max_length=1024)),
                ('file_name', models.CharField(db_column='FileName', max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True, db_column='UploadDate')),
                ('bill', models.ForeignKey(blank=True, db_column='BillID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.bill')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('invoice', models.ForeignKey(blank=True, db_column='InvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.invoice')),
                ('vendor', models.ForeignKey(blank=True, db_column='VendorID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor')),
            ],
            options={
                'db_table': 'Documents',
            },
        ),
    ]
