# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='Budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='project',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='CustomerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='EndDate',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectName',
            field=models.CharField(max_length=200, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Project Notes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='StartDate',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Status',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
    ]
