# Generated by Django 5.2.6 on 2025-09-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountCode', models.CharField(max_length=20)),
                ('AccountName', models.CharField(max_length=100)),
                ('AccountType', models.CharField(max_length=50)),
                ('AccountNotes', models.TextField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ChartOfAccounts',
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateTimeField()),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('DebitAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('CreditAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('GLNotes', models.TextField(blank=True, null=True)),
                ('CurrencyCode', models.CharField(default='USD', max_length=3)),
                ('ExchangeRate', models.DecimalField(decimal_places=6, default=1.0, max_digits=10)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'GeneralLedger',
            },
        ),
    ]
