# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccount',
            options={'verbose_name': 'Chart of Account', 'verbose_name_plural': 'Chart of Accounts'},
        ),
        migrations.AlterModelOptions(
            name='generalledger',
            options={'verbose_name': 'General Ledger Entry', 'verbose_name_plural': 'General Ledger'},
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='AccountCode',
            field=models.CharField(max_length=20, verbose_name='Account Code'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='AccountID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='AccountName',
            field=models.CharField(max_length=100, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='AccountNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Account Notes'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='AccountType',
            field=models.CharField(max_length=50, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='IsActive',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='AccountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccount', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='CreditAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Credit Amount'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='CurrencyCode',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='DebitAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Debit Amount'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='ExchangeRate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Exchange Rate'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='GLNotes',
            field=models.TextField(blank=True, null=True, verbose_name='GL Notes'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='TransactionDate',
            field=models.DateTimeField(verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='TransactionID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
