# Generated by Django 5.2.4 on 2025-07-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('location_id', models.AutoField(db_column='LocationID', primary_key=True, serialize=False)),
                ('location_name', models.CharField(db_column='LocationName', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'InventoryLocations',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(db_column='InventoryID', primary_key=True, serialize=False)),
                ('product_code', models.CharField(db_column='ProductCode', max_length=100)),
                ('product_name', models.CharField(db_column='ProductName', max_length=255)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('unit_price', models.DecimalField(db_column='UnitPrice', decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(db_column='CostPrice', decimal_places=2, max_digits=10)),
                ('inventory_notes', models.TextField(blank=True, db_column='InventoryNotes', null=True)),
                ('valuation_method', models.CharField(db_column='ValuationMethod', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('location', models.ForeignKey(blank=True, db_column='LocationID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorylocation')),
            ],
            options={
                'db_table': 'Inventory',
                'unique_together': {('company', 'product_code')},
            },
        ),
    ]
