# Generated by Django 5.2.4 on 2025-07-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('tax_rate_id', models.AutoField(db_column='TaxRateID', primary_key=True, serialize=False)),
                ('tax_name', models.CharField(db_column='TaxName', max_length=100)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=4, max_digits=6)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=100, null=True)),
                ('tax_regime', models.CharField(blank=True, db_column='TaxRegime', max_length=100, null=True)),
                ('effective_date', models.DateField(db_column='EffectiveDate')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'TaxRates',
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('tax_transaction_id', models.AutoField(db_column='TaxTransactionID', primary_key=True, serialize=False)),
                ('tax_amount', models.DecimalField(db_column='TaxAmount', decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField(db_column='TransactionDate')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('bill', models.ForeignKey(blank=True, db_column='BillID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.bill')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('invoice', models.ForeignKey(blank=True, db_column='InvoiceID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.invoice')),
                ('tax_rate', models.ForeignKey(db_column='TaxRateID', on_delete=django.db.models.deletion.CASCADE, to='tax.taxrate')),
            ],
            options={
                'db_table': 'TaxTransactions',
            },
        ),
    ]
