# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardmetric',
            options={'verbose_name': 'Dashboard Metric', 'verbose_name_plural': 'Dashboard Metrics'},
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='MetricID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Metric ID'),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='UpdatedDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='Value',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Value'),
        ),
    ]
