# Generated by Django 5.2.4 on 2025-07-29 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('subscriptions', '0001_initial'), ('subscriptions', '0002_alter_subscription_options_and_more')]

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('billing_cycle', models.CharField(max_length=50)),
                ('renewal_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'db_table': 'Subscriptions',
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
