# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importfile',
            options={'verbose_name': 'Import File', 'verbose_name_plural': 'Import Files'},
        ),
        migrations.AlterField(
            model_name='importerror',
            name='ErrorMessage',
            field=models.TextField(verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='importerror',
            name='ImportFileID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='importer.importfile', verbose_name='Import File'),
        ),
        migrations.AlterField(
            model_name='importerror',
            name='RowNumber',
            field=models.IntegerField(null=True, verbose_name='Row Number'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='File',
            field=models.FileField(upload_to='import_files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='FileType',
            field=models.CharField(choices=[('coa', 'Chart of Accounts'), ('customers', 'Customers'), ('vendors', 'Vendors'), ('invoices', 'Invoices'), ('bills', 'Bills')], max_length=20, verbose_name='File Type'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='Status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='UploadedAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterModelTable(
            name='importfile',
            table='ImportFiles',
        ),
    ]
