# Generated by Django 5.2.4 on 2025-07-15 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(null=True)),
                ('error_message', models.TextField()),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='importer.importfile')),
            ],
            options={
                'verbose_name': 'Import Error',
                'verbose_name_plural': 'Import Errors',
                'db_table': 'ImportErrors',
            },
        ),
    ]
