# Generated by Django 5.0.14 on 2025-07-25 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('exchange_rate_id', models.AutoField(db_column='ExchangeRateID', primary_key=True, serialize=False)),
                ('from_currency', models.CharField(db_column='FromCurrency', max_length=3)),
                ('to_currency', models.CharField(db_column='ToCurrency', max_length=3)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=6, max_digits=15)),
                ('effective_date', models.DateField(db_column='EffectiveDate')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
            ],
            options={
                'db_table': 'ExchangeRates',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(db_column='BudgetID', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='Description')),
                ('budget_year', models.IntegerField(db_column='BudgetYear')),
                ('budget_month', models.IntegerField(db_column='BudgetMonth')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=15)),
                ('budget_notes', models.TextField(blank=True, db_column='BudgetNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('account', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, to='core.chartofaccounts')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('asset_id', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('asset_name', models.CharField(db_column='AssetName', max_length=255)),
                ('asset_tag_number', models.CharField(blank=True, db_column='AssetTagNumber', max_length=50, null=True)),
                ('purchase_date', models.DateField(db_column='PurchaseDate')),
                ('purchase_cost', models.DecimalField(db_column='PurchaseCost', decimal_places=2, max_digits=15)),
                ('depreciation_method', models.CharField(db_column='DepreciationMethod', max_length=50)),
                ('useful_life_years', models.IntegerField(db_column='UsefulLifeYears')),
                ('asset_notes', models.TextField(blank=True, db_column='AssetNotes', null=True)),
                ('current_value', models.DecimalField(db_column='CurrentValue', decimal_places=2, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('disposal_date', models.DateField(blank=True, db_column='DisposalDate', null=True)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'FixedAssets',
            },
        ),
    ]
