# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_options_alter_vendor_address_and_more'),
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'verbose_name': 'Bill', 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='BillDate',
            field=models.DateField(verbose_name='Bill Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='BillID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Bill ID'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='BillNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Bill Notes'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='BillNumber',
            field=models.CharField(max_length=50, verbose_name='Bill Number'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='CurrencyCode',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='DueDate',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='ModifiedDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='VendorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor', verbose_name='Vendor'),
        ),
    ]
