# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-ActionDate'], 'verbose_name': 'Audit Log Entry', 'verbose_name_plural': 'Audit Log'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='Action',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ActionDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Action Date'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ActionDescription',
            field=models.CharField(max_length=255, verbose_name='Action Description'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ActionType',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('read', 'Read'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete'), ('other', 'Other')], default='other', max_length=50, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='AuditID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Audit ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ContentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='DataAfter',
            field=models.JSONField(blank=True, null=True, verbose_name='Data After'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='DataBefore',
            field=models.JSONField(blank=True, null=True, verbose_name='Data Before'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='Details',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='IPAddress',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ObjectID',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='RecordID',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Record ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='TableName',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True, verbose_name='Table Name'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='UserAgent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
