# Generated by Django 5.2.4 on 2025-07-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank_account_id', models.AutoField(db_column='BankAccountID', primary_key=True, serialize=False)),
                ('account_number', models.CharField(db_column='AccountNumber', max_length=50)),
                ('bank_name', models.CharField(db_column='BankName', max_length=255)),
                ('account_type', models.CharField(db_column='AccountType', default='Checking', max_length=50)),
                ('bank_acct_notes', models.TextField(blank=True, db_column='BankAcctNotes', null=True)),
                ('currency_code', models.CharField(db_column='CurrencyCode', default='USD', max_length=3)),
                ('balance', models.DecimalField(db_column='Balance', decimal_places=2, default=0.0, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'BankAccounts',
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('bank_transaction_id', models.AutoField(db_column='BankTransactionID', primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(db_column='TransactionDate')),
                ('transaction_number', models.CharField(blank=True, db_column='TransactionNumber', max_length=100, null=True)),
                ('description', models.TextField(db_column='Description')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(db_column='TransactionType', max_length=50)),
                ('reconciled', models.BooleanField(db_column='Reconciled', default=False)),
                ('is_imported', models.BooleanField(db_column='IsImported', default=False)),
                ('match_status', models.CharField(blank=True, db_column='MatchStatus', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('bank_account', models.ForeignKey(db_column='BankAccountID', on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount')),
                ('general_ledger', models.ForeignKey(blank=True, db_column='GeneralLedgerID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.generalledger')),
            ],
            options={
                'db_table': 'BankTransactions',
            },
        ),
    ]
