# Generated by Django 5.2.4 on 2025-07-29 00:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('payroll', '0001_initial'), ('payroll', '0002_remove_deduction_paystub_remove_paystub_employee_and_more')]

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_rename_customer_name_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('created_date', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('employee_notes', models.TextField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('name', models.CharField(default='Employee', max_length=200)),
                ('tax_withholding', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('taxes_withheld', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
            ],
            options={
                'db_table': 'Payroll',
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('deduction_id', models.AutoField(primary_key=True, serialize=False)),
                ('deduction_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
            options={
                'db_table': 'PayrollDeductions',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('time_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=18)),
                ('time_entry_notes', models.TextField(blank=True, null=True)),
                ('billable', models.BooleanField(default=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_time_entries', to='payroll.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'db_table': 'PayrollTimeEntries',
            },
        ),
    ]
