# Generated by Django 5.2.4 on 2025-07-06 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField()),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(primary_key=True, serialize=False)),
                ('run_date', models.DateField()),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'Payroll',
            },
        ),
        migrations.CreateModel(
            name='Paystub',
            fields=[
                ('paystub_id', models.AutoField(primary_key=True, serialize=False)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
            options={
                'db_table': 'Paystubs',
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('deduction_id', models.AutoField(primary_key=True, serialize=False)),
                ('deduction_name', models.CharField(max_length=100)),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paystub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.paystub')),
            ],
            options={
                'db_table': 'Deductions',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('benefit_id', models.AutoField(primary_key=True, serialize=False)),
                ('benefit_name', models.CharField(max_length=100)),
                ('benefit_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paystub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.paystub')),
            ],
            options={
                'db_table': 'Benefits',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('tax_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paystub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.paystub')),
            ],
            options={
                'db_table': 'Taxes',
            },
        ),
    ]
