# Generated by Django 5.2.6 on 2025-09-25 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('HourlyRate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('TaxWithholding', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('EmployeeNotes', models.TextField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('PayrollID', models.AutoField(primary_key=True, serialize=False)),
                ('PayPeriodStart', models.DateField()),
                ('PayPeriodEnd', models.DateField()),
                ('GrossPay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('NetPay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TaxesWithheld', models.DecimalField(decimal_places=2, max_digits=18)),
                ('PaymentDate', models.DateField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'db_table': 'Payroll',
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('DeductionID', models.AutoField(primary_key=True, serialize=False)),
                ('DeductionType', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('PayrollID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
            options={
                'db_table': 'PayrollDeductions',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('TimeEntryID', models.AutoField(primary_key=True, serialize=False)),
                ('WorkDate', models.DateField()),
                ('Hours', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TimeEntryNotes', models.TextField(blank=True, null=True)),
                ('Billable', models.BooleanField(default=False)),
                ('Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_time_entries', to='payroll.employee')),
            ],
            options={
                'db_table': 'PayrollTimeEntries',
            },
        ),
    ]
