# Generated by Django 5.0.14 on 2025-09-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayStub',
            fields=[
                ('PayStubID', models.AutoField(primary_key=True, serialize=False)),
                ('GrossPay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('NetPay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TotalDeductions', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TotalTaxes', models.DecimalField(decimal_places=2, max_digits=18)),
                ('PayPeriodStart', models.DateField()),
                ('PayPeriodEnd', models.DateField()),
                ('PaymentDate', models.DateField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('PayrollID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
            options={
                'db_table': 'PayStubs',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('TaxID', models.AutoField(primary_key=True, serialize=False)),
                ('TaxType', models.CharField(max_length=100)),
                ('TaxRate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('TaxAmount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TaxYear', models.IntegerField()),
                ('TaxPeriod', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('PayrollID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
            options={
                'db_table': 'Taxes',
            },
        ),
    ]
