# Generated by Django 5.0.14 on 2025-09-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_paystub_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('BenefitID', models.AutoField(primary_key=True, serialize=False)),
                ('BenefitType', models.CharField(max_length=100)),
                ('Provider', models.CharField(blank=True, max_length=200, null=True)),
                ('CoverageAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('EmployeeContribution', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('EmployerContribution', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('BenefitNotes', models.TextField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'db_table': 'Benefits',
            },
        ),
    ]
