# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_alter_project_budget_and_more'),
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('payroll', '0004_benefit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Benefit', 'verbose_name_plural': 'Benefits'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'verbose_name': 'Payroll', 'verbose_name_plural': 'Payrolls'},
        ),
        migrations.AlterModelOptions(
            name='payrolldeduction',
            options={'verbose_name': 'Payroll Deduction', 'verbose_name_plural': 'Payroll Deductions'},
        ),
        migrations.AlterModelOptions(
            name='paystub',
            options={'verbose_name': 'Pay Stub', 'verbose_name_plural': 'Pay Stubs'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name': 'Tax', 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'Time Entry', 'verbose_name_plural': 'Time Entries'},
        ),
        migrations.AlterField(
            model_name='benefit',
            name='BenefitID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Benefit ID'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='BenefitNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Benefit Notes'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='BenefitType',
            field=models.CharField(max_length=100, verbose_name='Benefit Type'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='CoverageAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Coverage Amount'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='EmployeeContribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Employee Contribution'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='EmployerContribution',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Employer Contribution'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='EndDate',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='IsActive',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='Provider',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='StartDate',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Employee Notes'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='HourlyRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Hourly Rate'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='TaxWithholding',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Tax Withholding'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='GrossPay',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Gross Pay'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='NetPay',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Net Pay'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='PayPeriodEnd',
            field=models.DateField(verbose_name='Pay Period End'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='PayPeriodStart',
            field=models.DateField(verbose_name='Pay Period Start'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='PaymentDate',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='PayrollID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Payroll ID'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='TaxesWithheld',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Taxes Withheld'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='DeductionID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Deduction ID'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='DeductionType',
            field=models.CharField(max_length=100, verbose_name='Deduction Type'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='payrolldeduction',
            name='PayrollID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll', verbose_name='Payroll'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='GrossPay',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Gross Pay'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='NetPay',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Net Pay'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='PayPeriodEnd',
            field=models.DateField(verbose_name='Pay Period End'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='PayPeriodStart',
            field=models.DateField(verbose_name='Pay Period Start'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='PayStubID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Pay Stub ID'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='PaymentDate',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='PayrollID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll', verbose_name='Payroll'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='TotalDeductions',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total Deductions'),
        ),
        migrations.AlterField(
            model_name='paystub',
            name='TotalTaxes',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total Taxes'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='PayrollID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll', verbose_name='Payroll'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='TaxAmount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='TaxID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='TaxPeriod',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax Period'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='TaxRate',
            field=models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='TaxType',
            field=models.CharField(max_length=100, verbose_name='Tax Type'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='TaxYear',
            field=models.IntegerField(verbose_name='Tax Year'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='Billable',
            field=models.BooleanField(default=False, verbose_name='Billable'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='EmployeeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_time_entries', to='payroll.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='Hours',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='ProjectID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_time_entries', to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='Rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='TimeEntryID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Time Entry ID'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='TimeEntryNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Time Entry Notes'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='WorkDate',
            field=models.DateField(verbose_name='Work Date'),
        ),
    ]
