# Generated by Django 5.0.14 on 2025-07-25 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('custom_field_id', models.AutoField(db_column='CustomFieldID', primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_column='FieldName', max_length=100)),
                ('field_type', models.CharField(db_column='FieldType', max_length=50)),
                ('table_name', models.CharField(db_column='TableName', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'CustomFields',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('value_id', models.AutoField(db_column='ValueID', primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(db_column='RecordID')),
                ('value', models.TextField(db_column='Value')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('custom_field', models.ForeignKey(db_column='CustomFieldID', on_delete=django.db.models.deletion.CASCADE, to='customization.customfield')),
            ],
            options={
                'db_table': 'CustomFieldValues',
            },
        ),
    ]
