# Generated by Django 5.2.6 on 2025-09-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('SubscriptionID', models.AutoField(primary_key=True, serialize=False)),
                ('PlanName', models.CharField(max_length=100)),
                ('BillingCycle', models.CharField(max_length=50)),
                ('RenewalDate', models.DateField()),
                ('Status', models.CharField(default='Active', max_length=20)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'Subscriptions',
            },
        ),
    ]
