# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='BillingCycle',
            field=models.CharField(max_length=50, verbose_name='Billing Cycle'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='PlanName',
            field=models.CharField(max_length=100, verbose_name='Plan Name'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='RenewalDate',
            field=models.DateField(verbose_name='Renewal Date'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Status',
            field=models.CharField(default='Active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='SubscriptionID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Subscription ID'),
        ),
    ]
