# Generated by Django 5.0.14 on 2025-07-25 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=254)),
                ('hourly_rate', models.DecimalField(db_column='HourlyRate', decimal_places=2, max_digits=15)),
                ('tax_withholding', models.DecimalField(db_column='TaxWithholding', decimal_places=2, max_digits=15)),
                ('employee_notes', models.TextField(blank=True, db_column='EmployeeNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.AutoField(db_column='PayrollID', primary_key=True, serialize=False)),
                ('pay_period_start', models.DateField(db_column='PayPeriodStart')),
                ('pay_period_end', models.DateField(db_column='PayPeriodEnd')),
                ('gross_pay', models.DecimalField(db_column='GrossPay', decimal_places=2, max_digits=15)),
                ('net_pay', models.DecimalField(db_column='NetPay', decimal_places=2, max_digits=15)),
                ('taxes_withheld', models.DecimalField(db_column='TaxesWithheld', decimal_places=2, max_digits=15)),
                ('payment_date', models.DateField(db_column='PaymentDate')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
            options={
                'db_table': 'Payroll',
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('deduction_id', models.AutoField(db_column='DeductionID', primary_key=True, serialize=False)),
                ('deduction_type', models.CharField(db_column='DeductionType', max_length=100)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('employee', models.ForeignKey(db_column='EmployeeID', on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('payroll', models.ForeignKey(db_column='PayrollID', on_delete=django.db.models.deletion.CASCADE, to='payroll.payroll')),
            ],
            options={
                'db_table': 'PayrollDeductions',
            },
        ),
    ]
