# Generated by Django 5.2.4 on 2025-07-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(db_column='SubscriptionID', primary_key=True, serialize=False)),
                ('plan_name', models.CharField(db_column='PlanName', max_length=100)),
                ('billing_cycle', models.CharField(db_column='BillingCycle', max_length=50)),
                ('renewal_date', models.DateTimeField(db_column='RenewalDate')),
                ('status', models.CharField(db_column='Status', default='Active', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'db_table': 'Subscriptions',
            },
        ),
    ]
