# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usercompanyrole',
            options={'verbose_name': 'User Company Role', 'verbose_name_plural': 'User Company Roles'},
        ),
        migrations.AlterField(
            model_name='company',
            name='AdminUserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_companies', to=settings.AUTH_USER_MODEL, verbose_name='Admin User'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Company ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyName',
            field=models.CharField(max_length=100, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Company Notes'),
        ),
        migrations.AlterField(
            model_name='company',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserNotes',
            field=models.TextField(blank=True, null=True, verbose_name='User Notes'),
        ),
        migrations.AlterField(
            model_name='usercompanyrole',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='usercompanyrole',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='usercompanyrole',
            name='Role',
            field=models.CharField(max_length=50, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='usercompanyrole',
            name='UserCompanyRoleID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='User Company Role ID'),
        ),
        migrations.AlterField(
            model_name='usercompanyrole',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('EmailNotifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('DesktopNotifications', models.BooleanField(default=False, verbose_name='Desktop Notifications')),
                ('NotificationTypes', models.JSONField(default=dict, help_text='Which types of notifications to receive', verbose_name='Notification Types')),
                ('AutoSaveForms', models.BooleanField(default=True, verbose_name='Auto-save Forms')),
                ('DateFormat', models.CharField(default='MM/DD/YYYY', max_length=20, verbose_name='Date Format')),
                ('CurrencyFormat', models.CharField(default='USD', max_length=10, verbose_name='Currency Format')),
                ('Theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=20, verbose_name='Theme')),
                ('TwoFactorEnabled', models.BooleanField(default=False, verbose_name='Two-Factor Authentication')),
                ('SessionTimeout', models.IntegerField(default=30, verbose_name='Session Timeout (minutes)')),
                ('LastExportDate', models.DateTimeField(blank=True, null=True, verbose_name='Last Export Date')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('ModifiedDate', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('DefaultCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='accounts.company', verbose_name='Default Company')),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'db_table': 'UserSettings',
            },
        ),
    ]
