# Generated by Django 5.2.6 on 2025-09-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('CustomFieldID', models.AutoField(primary_key=True, serialize=False)),
                ('FieldName', models.CharField(max_length=255)),
                ('FieldType', models.CharField(max_length=50)),
                ('TableName', models.CharField(max_length=255)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'CustomFields',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('ValueID', models.AutoField(primary_key=True, serialize=False)),
                ('RecordID', models.IntegerField()),
                ('Value', models.TextField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CustomFieldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customfields.customfield')),
            ],
            options={
                'db_table': 'CustomFieldValues',
            },
        ),
    ]
