# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('customfields', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'verbose_name': 'Custom Field', 'verbose_name_plural': 'Custom Fields'},
        ),
        migrations.AlterModelOptions(
            name='customfieldvalue',
            options={'verbose_name': 'Custom Field Value', 'verbose_name_plural': 'Custom Field Values'},
        ),
        migrations.AlterField(
            model_name='customfield',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='CustomFieldID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Custom Field ID'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='FieldName',
            field=models.CharField(max_length=255, verbose_name='Field Name'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='FieldType',
            field=models.CharField(max_length=50, verbose_name='Field Type'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='TableName',
            field=models.CharField(max_length=255, verbose_name='Table Name'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='CustomFieldID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customfields.customfield', verbose_name='Custom Field'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='RecordID',
            field=models.IntegerField(verbose_name='Record ID'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='Value',
            field=models.TextField(verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='ValueID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Value ID'),
        ),
    ]
