# Generated by Django 5.0.14 on 2025-09-29 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('BudgetID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(blank=True, null=True)),
                ('BudgetYear', models.IntegerField()),
                ('BudgetMonth', models.IntegerField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('BudgetNotes', models.TextField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('AccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccount')),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Budgets',
            },
        ),
    ]
