# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_alter_chartofaccount_options_and_more'),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='AccountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccount', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='BudgetID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Budget ID'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='BudgetMonth',
            field=models.IntegerField(verbose_name='Budget Month'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='BudgetNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Budget Notes'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='BudgetYear',
            field=models.IntegerField(verbose_name='Budget Year'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
