# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integration',
            options={'verbose_name': 'Integration', 'verbose_name_plural': 'Integrations'},
        ),
        migrations.AlterField(
            model_name='integration',
            name='APIKey',
            field=models.CharField(max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='IntegrationID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Integration ID'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='IntegrationType',
            field=models.CharField(max_length=100, verbose_name='Integration Type'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='Settings',
            field=models.JSONField(blank=True, null=True, verbose_name='Settings'),
        ),
    ]
