# Generated by Django 5.2.6 on 2025-09-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bills', '0001_initial'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DocumentID', models.AutoField(primary_key=True, serialize=False)),
                ('FilePath', models.CharField(max_length=255)),
                ('FileName', models.CharField(max_length=100)),
                ('UploadDate', models.DateTimeField(auto_now_add=True)),
                ('BillID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.bill')),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('CustomerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('InvoiceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice')),
                ('VendorID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor')),
            ],
            options={
                'db_table': 'Documents',
            },
        ),
    ]
