# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_options_alter_invoice_companyid_and_more'),
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('vendors', '0002_alter_vendor_options_alter_vendor_address_and_more'),
        ('bills', '0002_alter_bill_options_alter_bill_billdate_and_more'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='document',
            name='BillID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.bill', verbose_name='Bill'),
        ),
        migrations.AlterField(
            model_name='document',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='document',
            name='CustomerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='document',
            name='DocumentID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Document ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='FileName',
            field=models.CharField(max_length=100, verbose_name='File Name'),
        ),
        migrations.AlterField(
            model_name='document',
            name='FilePath',
            field=models.CharField(max_length=255, verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='document',
            name='InvoiceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='document',
            name='UploadDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Upload Date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='VendorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendor', verbose_name='Vendor'),
        ),
    ]
