# Generated by Django 5.0.14 on 2025-09-29 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('IntegrationID', models.AutoField(primary_key=True, serialize=False)),
                ('IntegrationType', models.CharField(max_length=100)),
                ('APIKey', models.CharField(max_length=255)),
                ('Settings', models.JSONField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'Integrations',
            },
        ),
    ]
