# Generated by Django 5.2.6 on 2025-09-25 19:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('AuditID', models.AutoField(primary_key=True, serialize=False)),
                ('ActionType', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('read', 'Read'), ('view', 'View'), ('update', 'Update'), ('delete', 'Delete'), ('other', 'Other')], default='other', max_length=50)),
                ('ActionDescription', models.CharField(max_length=255)),
                ('ObjectID', models.CharField(blank=True, max_length=255, null=True)),
                ('Action', models.CharField(blank=True, max_length=255, null=True)),
                ('TableName', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
                ('RecordID', models.IntegerField(blank=True, default=0, null=True)),
                ('DataBefore', models.JSONField(blank=True, null=True)),
                ('DataAfter', models.JSONField(blank=True, null=True)),
                ('Details', models.TextField(blank=True, null=True)),
                ('IPAddress', models.CharField(blank=True, max_length=45, null=True)),
                ('UserAgent', models.TextField(blank=True, null=True)),
                ('ActionDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('ContentType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AuditLog',
                'ordering': ['-ActionDate'],
            },
        ),
    ]
