# Generated by Django 5.2.4 on 2025-07-29 00:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('audit', '0001_initial'), ('audit', '0002_auto_20250728_1938'), ('audit', '0003_alter_auditlog_options_and_more')]

    dependencies = [
        ('accounts', '0005_user_profile_photo'),
        ('accounts', '0006_remove_company_address_remove_company_city_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(blank=True, default=0, null=True)),
                ('table_name', models.CharField(blank=True, default='Unknown', max_length=100, null=True)),
            ],
            options={
                'ordering': ['-action_date'],
                'indexes': [],
                'db_table': 'AuditLog',
            },
        ),
    ]
