# Generated by Django 5.2.4 on 2025-07-06 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_users_alter_company_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='companies', through='accounts.UserCompanyRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
