# Generated by Django 5.2.6 on 2025-09-25 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('InvoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceNumber', models.CharField(max_length=50)),
                ('InvoiceDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Status', models.CharField(max_length=20)),
                ('InvoiceNotes', models.TextField(blank=True, null=True)),
                ('CurrencyCode', models.CharField(default='USD', max_length=3)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('SubscriptionID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Invoices',
            },
        ),
    ]
