# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_options_alter_customer_address_and_more'),
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('subscriptions', '0002_alter_subscription_billingcycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoices'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='CurrencyCode',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='CustomerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='DueDate',
            field=models.DateField(verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceDate',
            field=models.DateField(verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Invoice ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Invoice Notes'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='InvoiceNumber',
            field=models.CharField(max_length=50, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Status',
            field=models.CharField(max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='SubscriptionID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription', verbose_name='Subscription'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
