# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_options_alter_invoice_companyid_and_more'),
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('bills', '0002_alter_bill_options_alter_bill_billdate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='BillID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.bill', verbose_name='Bill'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='CurrencyCode',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='InvoiceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='PaymentDate',
            field=models.DateField(verbose_name='Payment Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='PaymentID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Payment ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='PaymentMethod',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='PaymentNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Notes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='UserID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
