# Generated by Django 5.0.14 on 2025-09-29 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bills', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('TaxRateID', models.AutoField(primary_key=True, serialize=False)),
                ('TaxName', models.CharField(max_length=100)),
                ('Rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Region', models.CharField(blank=True, max_length=100, null=True)),
                ('TaxRegime', models.CharField(blank=True, max_length=100, null=True)),
                ('EffectiveDate', models.DateField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'TaxRates',
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('TaxTransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('TaxAmount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TransactionDate', models.DateTimeField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('BillID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.bill')),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('InvoiceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice')),
                ('TaxRateID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.taxrate')),
            ],
            options={
                'db_table': 'TaxTransactions',
            },
        ),
    ]
