# Generated by Django 4.2.11 on 2025-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_options_alter_invoice_companyid_and_more'),
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('bills', '0002_alter_bill_options_alter_bill_billdate_and_more'),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrate',
            options={'verbose_name': 'Tax Rate', 'verbose_name_plural': 'Tax Rates'},
        ),
        migrations.AlterModelOptions(
            name='taxtransaction',
            options={'verbose_name': 'Tax Transaction', 'verbose_name_plural': 'Tax Transactions'},
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='EffectiveDate',
            field=models.DateField(verbose_name='Effective Date'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='Rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='Region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='TaxName',
            field=models.CharField(max_length=100, verbose_name='Tax Name'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='TaxRateID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Tax Rate ID'),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='TaxRegime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Regime'),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='BillID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.bill', verbose_name='Bill'),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='InvoiceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice', verbose_name='Invoice'),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='TaxAmount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='TaxRateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxes.taxrate', verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='TaxTransactionID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Tax Transaction ID'),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='TransactionDate',
            field=models.DateTimeField(verbose_name='Transaction Date'),
        ),
    ]
