# Generated by Django 5.2.6 on 2025-09-25 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('BillID', models.AutoField(primary_key=True, serialize=False)),
                ('BillNumber', models.CharField(max_length=50)),
                ('BillDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('Status', models.CharField(max_length=20)),
                ('BillNotes', models.TextField(blank=True, null=True)),
                ('CurrencyCode', models.CharField(default='USD', max_length=3)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('ModifiedDate', models.DateTimeField(auto_now=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('VendorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'db_table': 'Bills',
            },
        ),
    ]
