# Generated by Django 5.2.4 on 2025-07-22 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('integration_id', models.AutoField(db_column='IntegrationID', primary_key=True, serialize=False)),
                ('integration_type', models.CharField(db_column='IntegrationType', max_length=100)),
                ('api_key', models.CharField(blank=True, db_column='APIKey', max_length=255, null=True)),
                ('settings', models.TextField(blank=True, db_column='Settings', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'Integrations',
            },
        ),
    ]
