# Generated by Django 5.2.4 on 2025-07-28 23:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_company_address_remove_company_city_and_more'),
        ('core', '0001_initial'),
        ('inventory', '__first__'),
        ('subscriptions', '0002_alter_subscription_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='vendor_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(default='BIL-001', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='INV-001', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget_year', models.IntegerField()),
                ('budget_month', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('budget_notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_budgets', to='core.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_budgets', to='accounts.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CoreBudgets',
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('custom_field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'CustomFields',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('value_id', models.AutoField(primary_key=True, serialize=False)),
                ('record_id', models.IntegerField()),
                ('value', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customfield')),
            ],
            options={
                'db_table': 'CustomFieldValues',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('exchange_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('effective_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ExchangeRates',
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_tag_number', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('depreciation_method', models.CharField(max_length=50)),
                ('useful_life_years', models.IntegerField()),
                ('asset_notes', models.TextField(blank=True, null=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_fixed_assets', to='accounts.company')),
            ],
            options={
                'db_table': 'CoreFixedAssets',
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('integration_id', models.AutoField(primary_key=True, serialize=False)),
                ('integration_type', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_integrations', to='accounts.company')),
            ],
            options={
                'db_table': 'CoreIntegrations',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('inventory_notes', models.TextField(blank=True, null=True)),
                ('valuation_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_inventory', to='accounts.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_inventory', to='inventory.inventorylocation')),
            ],
            options={
                'db_table': 'CoreInventory',
            },
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_line_items', to='core.bill')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inventory')),
            ],
            options={
                'db_table': 'CoreBillLineItems',
            },
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_inventory_locations', to='accounts.company')),
            ],
            options={
                'db_table': 'CoreInventoryLocations',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('line_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inventory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_line_items', to='core.invoice')),
            ],
            options={
                'db_table': 'CoreInvoiceLineItems',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_notes', models.TextField(blank=True, null=True)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_payments', to='core.bill')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_payments', to='accounts.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_payments', to='core.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CorePayments',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('project_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_projects', to='accounts.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_projects', to='core.customer')),
            ],
            options={
                'db_table': 'CoreProjects',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('tax_rate_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_regime', models.CharField(blank=True, max_length=100, null=True)),
                ('effective_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_tax_rates', to='accounts.company')),
            ],
            options={
                'db_table': 'CoreTaxRates',
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('tax_transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_tax_transactions', to='core.bill')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_tax_transactions', to='accounts.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_tax_transactions', to='core.invoice')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_transactions', to='core.taxrate')),
            ],
            options={
                'db_table': 'CoreTaxTransactions',
            },
        ),
    ]
