# Generated by Django 5.2.4 on 2025-09-08 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial_squashed_0006_remove_company_address_remove_company_city_and_more'),
        ('core', '0002_rename_customer_name_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='account',
        ),
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.AddField(
            model_name='budget',
            name='account_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='inventory_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_month',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='budget',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='core_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_custom_fields', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='table_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='custom_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_custom_field_values', to='core.customfield'),
        ),
        migrations.AlterField(
            model_name='inventorylocation',
            name='location_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_invoice_line_items', to='core.invoice'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('record_id', models.IntegerField()),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_audit_logs', to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AuditLogs',
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('time_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.IntegerField()),
                ('work_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_entry_notes', models.TextField()),
                ('billable', models.BooleanField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_time_entries', to='core.project')),
            ],
            options={
                'db_table': 'CoreTimeEntries',
            },
        ),
        migrations.CreateModel(
            name='UserCompanyRole',
            fields=[
                ('user_company_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_user_company_roles', to='accounts.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_user_company_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserCompanyRoles',
            },
        ),
    ]
