# Generated by Django 5.2.4 on 2025-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_budget_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicelineitem',
            name='inventory_id',
            field=models.IntegerField(default=0),
        ),
    ]
