# Generated by Django 5.0.14 on 2025-09-29 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('AssetID', models.AutoField(primary_key=True, serialize=False)),
                ('AssetName', models.CharField(max_length=200)),
                ('AssetTagNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('PurchaseDate', models.DateField()),
                ('PurchaseCost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('DepreciationMethod', models.CharField(max_length=50)),
                ('UsefulLifeYears', models.IntegerField()),
                ('AssetNotes', models.TextField(blank=True, null=True)),
                ('CurrentValue', models.DecimalField(decimal_places=2, max_digits=18)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('DisposalDate', models.DateField(blank=True, null=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'FixedAssets',
            },
        ),
    ]
