# Generated by Django 5.2.4 on 2025-07-22 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(db_column='CompanyID', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='CompanyName', max_length=255)),
                ('company_notes', models.TextField(blank=True, db_column='CompanyNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('admin_user', models.ForeignKey(blank=True, db_column='AdminUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('account_id', models.AutoField(db_column='AccountID', primary_key=True, serialize=False)),
                ('account_code', models.CharField(db_column='AccountCode', max_length=20)),
                ('account_name', models.CharField(db_column='AccountName', max_length=255)),
                ('account_type', models.CharField(db_column='AccountType', max_length=50)),
                ('account_notes', models.TextField(blank=True, db_column='AccountNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'ChartOfAccounts',
                'unique_together': {('company', 'account_code')},
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('transaction_id', models.AutoField(db_column='TransactionID', primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(db_column='TransactionDate')),
                ('description', models.TextField(db_column='Description')),
                ('debit_amount', models.DecimalField(db_column='DebitAmount', decimal_places=2, default=0.0, max_digits=15)),
                ('credit_amount', models.DecimalField(db_column='CreditAmount', decimal_places=2, default=0.0, max_digits=15)),
                ('gl_notes', models.TextField(blank=True, db_column='GLNotes', null=True)),
                ('currency_code', models.CharField(db_column='CurrencyCode', default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1.0, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('account', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, to='core.chartofaccounts')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GeneralLedger',
            },
        ),
    ]
