# Generated by Django 5.2.4 on 2025-07-22 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(db_column='CompanyID', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_column='CompanyName', max_length=255)),
                ('company_notes', models.TextField(blank=True, db_column='CompanyNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('admin_user', models.ForeignKey(blank=True, db_column='AdminUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('account_id', models.AutoField(db_column='AccountID', primary_key=True, serialize=False)),
                ('account_code', models.CharField(db_column='AccountCode', max_length=20)),
                ('account_name', models.CharField(db_column='AccountName', max_length=255)),
                ('account_type', models.CharField(db_column='AccountType', max_length=50)),
                ('account_notes', models.TextField(blank=True, db_column='AccountNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'ChartOfAccounts',
                'unique_together': {('company', 'account_code')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(db_column='BudgetID', primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='Description')),
                ('budget_year', models.IntegerField(db_column='BudgetYear')),
                ('budget_month', models.IntegerField(db_column='BudgetMonth')),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=15)),
                ('budget_notes', models.TextField(blank=True, db_column='BudgetNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('user', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, to='core.chartofaccounts')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('payment_terms', models.CharField(blank=True, db_column='PaymentTerms', max_length=100, null=True)),
                ('customer_notes', models.TextField(blank=True, db_column='CustomerNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('custom_field_id', models.AutoField(db_column='CustomFieldID', primary_key=True, serialize=False)),
                ('field_name', models.CharField(db_column='FieldName', max_length=255)),
                ('field_type', models.CharField(db_column='FieldType', max_length=50)),
                ('table_name', models.CharField(db_column='TableName', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'CustomFields',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('value_id', models.AutoField(db_column='ValueID', primary_key=True, serialize=False)),
                ('record_id', models.IntegerField(db_column='RecordID')),
                ('value', models.TextField(db_column='Value')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('custom_field', models.ForeignKey(db_column='CustomFieldID', on_delete=django.db.models.deletion.CASCADE, to='core.customfield')),
            ],
            options={
                'db_table': 'CustomFieldValues',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('exchange_rate_id', models.AutoField(db_column='ExchangeRateID', primary_key=True, serialize=False)),
                ('from_currency', models.CharField(db_column='FromCurrency', max_length=3)),
                ('to_currency', models.CharField(db_column='ToCurrency', max_length=3)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=6, max_digits=10)),
                ('effective_date', models.DateField(db_column='EffectiveDate')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
            ],
            options={
                'db_table': 'ExchangeRates',
                'unique_together': {('from_currency', 'to_currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('asset_id', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('asset_name', models.CharField(db_column='AssetName', max_length=255)),
                ('asset_tag_number', models.CharField(blank=True, db_column='AssetTagNumber', max_length=100, null=True)),
                ('purchase_date', models.DateField(db_column='PurchaseDate')),
                ('purchase_cost', models.DecimalField(db_column='PurchaseCost', decimal_places=2, max_digits=15)),
                ('depreciation_method', models.CharField(db_column='DepreciationMethod', max_length=50)),
                ('useful_life_years', models.IntegerField(db_column='UsefulLifeYears')),
                ('asset_notes', models.TextField(blank=True, db_column='AssetNotes', null=True)),
                ('current_value', models.DecimalField(db_column='CurrentValue', decimal_places=2, max_digits=15)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('disposal_date', models.DateField(blank=True, db_column='DisposalDate', null=True)),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'FixedAssets',
            },
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('transaction_id', models.AutoField(db_column='TransactionID', primary_key=True, serialize=False)),
                ('transaction_date', models.DateField(db_column='TransactionDate')),
                ('description', models.TextField(db_column='Description')),
                ('debit_amount', models.DecimalField(db_column='DebitAmount', decimal_places=2, default=0.0, max_digits=15)),
                ('credit_amount', models.DecimalField(db_column='CreditAmount', decimal_places=2, default=0.0, max_digits=15)),
                ('gl_notes', models.TextField(blank=True, db_column='GLNotes', null=True)),
                ('currency_code', models.CharField(db_column='CurrencyCode', default='USD', max_length=3)),
                ('exchange_rate', models.DecimalField(db_column='ExchangeRate', decimal_places=6, default=1.0, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('account', models.ForeignKey(db_column='AccountID', on_delete=django.db.models.deletion.CASCADE, to='core.chartofaccounts')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('user', models.ForeignKey(db_column='UserID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GeneralLedger',
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('integration_id', models.AutoField(db_column='IntegrationID', primary_key=True, serialize=False)),
                ('integration_type', models.CharField(db_column='IntegrationType', max_length=100)),
                ('api_key', models.TextField(blank=True, db_column='APIKey', null=True)),
                ('settings', models.JSONField(blank=True, db_column='Settings', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'Integrations',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(db_column='ProjectID', primary_key=True, serialize=False)),
                ('project_name', models.CharField(db_column='ProjectName', max_length=255)),
                ('start_date', models.DateField(db_column='StartDate')),
                ('end_date', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('budget', models.DecimalField(blank=True, db_column='Budget', decimal_places=2, max_digits=15, null=True)),
                ('project_notes', models.TextField(blank=True, db_column='ProjectNotes', null=True)),
                ('status', models.CharField(db_column='Status', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('customer', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('tax_rate_id', models.AutoField(db_column='TaxRateID', primary_key=True, serialize=False)),
                ('tax_name', models.CharField(db_column='TaxName', max_length=255)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=6, max_digits=8)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=100, null=True)),
                ('tax_regime', models.CharField(blank=True, db_column='TaxRegime', max_length=100, null=True)),
                ('effective_date', models.DateField(db_column='EffectiveDate')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'TaxRates',
            },
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('tax_transaction_id', models.AutoField(db_column='TaxTransactionID', primary_key=True, serialize=False)),
                ('tax_amount', models.DecimalField(db_column='TaxAmount', decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateField(db_column='TransactionDate')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('bill', models.ForeignKey(blank=True, db_column='BillID', null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.bill')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('invoice', models.ForeignKey(blank=True, db_column='InvoiceID', null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.invoice')),
                ('tax_rate', models.ForeignKey(db_column='TaxRateID', on_delete=django.db.models.deletion.CASCADE, to='core.taxrate')),
            ],
            options={
                'db_table': 'TaxTransactions',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(db_column='VendorID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('payment_terms', models.CharField(blank=True, db_column='PaymentTerms', max_length=100, null=True)),
                ('vendor_notes', models.TextField(blank=True, db_column='VendorNotes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate')),
                ('company', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'db_table': 'Vendors',
            },
        ),
    ]
