# Generated by Django 5.2.6 on 2025-09-25 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bills', '0001_initial'),
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentDate', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('PaymentMethod', models.CharField(blank=True, max_length=50, null=True)),
                ('PaymentNotes', models.TextField(blank=True, null=True)),
                ('CurrencyCode', models.CharField(default='USD', max_length=3)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('BillID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bills.bill')),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('InvoiceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'Payments',
                'ordering': ['-PaymentDate'],
            },
        ),
    ]
