# Generated by Django 5.2.6 on 2025-09-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('VendorID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=255, null=True)),
                ('Phone', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('PaymentTerms', models.CharField(blank=True, max_length=50, null=True)),
                ('VendorNotes', models.TextField(blank=True, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'Vendors',
            },
        ),
    ]
