# Generated by Django 5.0.14 on 2025-09-29 15:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('BankAccountID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountNumber', models.CharField(max_length=50)),
                ('BankName', models.CharField(max_length=100)),
                ('AccountType', models.CharField(max_length=50)),
                ('BankAcctNotes', models.TextField(blank=True, null=True)),
                ('CurrencyCode', models.CharField(default='USD', max_length=3)),
                ('Balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CompanyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'db_table': 'BankAccounts',
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('BankStatementLineID', models.AutoField(primary_key=True, serialize=False)),
                ('TransactionDate', models.DateTimeField()),
                ('TransactionNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(max_length=255)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('TransactionType', models.CharField(max_length=50)),
                ('Reconciled', models.BooleanField(default=False)),
                ('IsImported', models.BooleanField(default=False)),
                ('MatchStatus', models.CharField(blank=True, max_length=50, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('BankAccountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount')),
                ('GeneralLedgerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.generalledger')),
            ],
            options={
                'db_table': 'BankStatementLines',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationEntry',
            fields=[
                ('ReconciliationEntryID', models.AutoField(primary_key=True, serialize=False)),
                ('ReconciledAmount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ReconciledDate', models.DateTimeField(auto_now_add=True)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('BankStatementLineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankstatementline')),
                ('GeneralLedgerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.generalledger')),
            ],
            options={
                'db_table': 'ReconciliationEntries',
            },
        ),
    ]
