# Generated by Django 4.2.11 on 2025-10-01 18:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_company_options_alter_user_options_and_more'),
        ('accounting', '0003_alter_chartofaccount_options_and_more'),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Bank Account', 'verbose_name_plural': 'Bank Accounts'},
        ),
        migrations.AlterModelOptions(
            name='bankstatementline',
            options={'verbose_name': 'Bank Statement Line', 'verbose_name_plural': 'Bank Statement Lines'},
        ),
        migrations.AlterModelOptions(
            name='reconciliationentry',
            options={'verbose_name': 'Reconciliation Entry', 'verbose_name_plural': 'Reconciliation Entries'},
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='AccountNumber',
            field=models.CharField(max_length=50, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='AccountType',
            field=models.CharField(max_length=50, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='Balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='BankAccountID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Bank Account ID'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='BankAcctNotes',
            field=models.TextField(blank=True, null=True, verbose_name='Bank Account Notes'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='BankName',
            field=models.CharField(max_length=100, verbose_name='Bank Name'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='CurrencyCode',
            field=models.CharField(default='USD', max_length=3, verbose_name='Currency Code'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='BankAccountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='BankStatementLineID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Bank Statement Line ID'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='Description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='GeneralLedgerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.generalledger', verbose_name='General Ledger Entry'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='IsImported',
            field=models.BooleanField(default=False, verbose_name='Is Imported'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='MatchStatus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Match Status'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='Reconciled',
            field=models.BooleanField(default=False, verbose_name='Reconciled'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='TransactionDate',
            field=models.DateTimeField(verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='TransactionNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Number'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='TransactionType',
            field=models.CharField(max_length=50, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='reconciliationentry',
            name='BankStatementLineID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.bankstatementline', verbose_name='Bank Statement Line'),
        ),
        migrations.AlterField(
            model_name='reconciliationentry',
            name='GeneralLedgerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.generalledger', verbose_name='General Ledger Entry'),
        ),
        migrations.AlterField(
            model_name='reconciliationentry',
            name='Notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='reconciliationentry',
            name='ReconciledAmount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Reconciled Amount'),
        ),
        migrations.AlterField(
            model_name='reconciliationentry',
            name='ReconciledDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reconciled Date'),
        ),
        migrations.AlterField(
            model_name='reconciliationentry',
            name='ReconciliationEntryID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Reconciliation Entry ID'),
        ),
    ]
